unsigned char myReadByte(unsigned short);
int myWriteByte(unsigned short, unsigned char);
void i2cIdle(void);
void i2cStart(void);
int i2cWrite(unsigned char);
unsigned char i2cRead(void);
void i2cRestart(void);
void i2cStop(void);
void eepromRead(int);
void eepromWrite(int, char);
void eepromCalc(char);
